### ISSUE TITLE
Error in insert of legacy activities

### ISSUE THREAD

**Issue by neeesn** [praxisdigital/moodle-block_sharing_cart#137] opened 2024-05-02 07:40 UTC
When insterting activities on mitnielsbrock test site i get the error below.
Kursus: https://mitnielsbrock-dk.moodle.moxis.dk/course/view.php?id=49980&section=1
https://go.screenpal.com/watch/cZhniAVMg0M

(opgaven kommer ind i forløbet - jeg får vist sagt at den ikke kommer ind)

Missing id for section state update
Error: Missing id for section state update
    at _exports.default.get (https://mitnielsbrock-dk.moodle.moxis.dk/lib/requirejs.php/1714636390/core/first.js:683:4517)
    at https://mitnielsbrock-dk.moodle.moxis.dk/lib/requirejs.php/1714636390/core/first.js:1775:7061
    at Array.forEach (<anonymous>)
    at _exports.default._setElementsValue (https://mitnielsbrock-dk.moodle.moxis.dk/lib/requirejs.php/1714636390/core/first.js:1775:7020)
    at _exports.default.sectionLock (https://mitnielsbrock-dk.moodle.moxis.dk/lib/requirejs.php/1714636390/core/first.js:1775:6855)
    at _exports.default.sectionState (https://mitnielsbrock-dk.moodle.moxis.dk/lib/requirejs.php/1714636390/core/first.js:1775:11196)
    at _default.dispatch (https://mitnielsbrock-dk.moodle.moxis.dk/lib/requirejs.php/1714636390/core/first.js:665:4838)
    at _default.dispatch (https://mitnielsbrock-dk.moodle.moxis.dk/lib/requirejs.php/1714636390/core/first.js:1716:5626)
    at _exports.default.loadQueue (https://mitnielsbrock-dk.moodle.moxis.dk/lib/requirejs.php/1714636390/core/first.js:4600:3165)

Det sker også ved nye aktiviteter, på deres test site.

**Comment by frederikmillingpytlick** [comment] 2024-05-03 09:11
Fixed in #133

**Comment by neeesn** [comment] 2024-05-13 09:33
@frederikmillingpytlick it seems theres an issue with copy from sharing cart to course. If you click on the run now button more than once this error is presented:
Can't find data record in database table task_adhoc.
File: /lib/dml/moodle_database.php
Line: 1654
Stack trace:
SELECT * FROM {task_adhoc} WHERE id = ? AND component = ? AND faildelay = ? AND timestarted IS NULL AND userid = ?
[array (
  0 => 784694,
  1 => 'block_sharing_cart',
  2 => 0,
  3 => '2',
)]
Error code: invalidrecord
* line 1654 of /lib/dml/moodle_database.php: dml_missing_record_exception thrown
* line 1630 of /lib/dml/moodle_database.php: call to moodle_database->get_record_select()
* line 48 of /blocks/sharing_cart/classes/external/task/run_now.php: call to moodle_database->get_record()
* line ? of unknownfile: call to block_sharing_cart\external\task\run_now::execute()
* line 253 of /lib/external/classes/external_api.php: call to call_user_func_array()
* line 83 of /lib/ajax/service.php: call to core_external\external_api::call_external_function()

The activity do appear in the sharing cart, and can be copied into the course again without any problems. Link to video showing the error: https://go.screenpal.com/watch/cZhIQTVLQ6a

**Comment by frederikmillingpytlick** [comment] 2024-05-14 10:59
> [@frederikmillingpytlick](https://github.com/frederikmillingpytlick) it seems theres an issue with copy from sharing cart to course. If you click on the run now button more than once this error is presented: Can't find data record in database table task_adhoc. File: /lib/dml/moodle_database.php Line: 1654 Stack trace: SELECT * FROM {task_adhoc} WHERE id = ? AND component = ? AND faildelay = ? AND timestarted IS NULL AND userid = ? [array ( 0 => 784694, 1 => 'block_sharing_cart', 2 => 0, 3 => '2', )] Error code: invalidrecord
> 
> * line 1654 of /lib/dml/moodle_database.php: dml_missing_record_exception thrown
> * line 1630 of /lib/dml/moodle_database.php: call to moodle_database->get_record_select()
> * line 48 of /blocks/sharing_cart/classes/external/task/run_now.php: call to moodle_database->get_record()
> * line ? of unknownfile: call to block_sharing_cart\external\task\run_now::execute()
> * line 253 of /lib/external/classes/external_api.php: call to call_user_func_array()
> * line 83 of /lib/ajax/service.php: call to core_external\external_api::call_external_function()
> 
> The activity do appear in the sharing cart, and can be copied into the course again without any problems. Link to video showing the error: https://go.screenpal.com/watch/cZhIQTVLQ6a

@neeesn fixed in the newest version :)

**Comment by superfoght** [comment] 2024-05-22 09:04
Can't reproduce it anymore

**Comment by neeesn** [comment] 2024-06-24 08:01
Now you cannot insert legacy activities at all.

**Comment by neeesn** [comment] 2024-06-24 08:14
You can test here: https://kundeteam.moodle.moxis.dk/course/view.php?id=25&sectionid=237

**Closed** 2024-07-01 06:20 UTC
Labels: bug
