### ISSUE TITLE
Copy section on nielsbrock generates an error

### ISSUE THREAD

**Issue by superfoght** [praxisdigital/moodle-block_sharing_cart#105] opened 2023-11-16 12:12 UTC
https://www.mitnielsbrock.dk/course/view.php?id=59338&section=39

on the above course, I copy the section 4.4. It takes a looooong time and finally generates this error: 

![Image](https://github.com/praxisdigital/moodle-block_sharing_cart/assets/2778015/3aee642d-b221-435b-ad4e-1bfce34a4891)

Note:
_Try to cleanup the unused files in the course and see if it helps with the backup process_.

**Comment by superfoght** [comment] 2023-11-16 12:13
The above error came from the client. When I tried to reproduce it, I got this error: 

undefined - Error
<html> <head><title>504 Gateway Time-out</title></head> <body> <center><h1>504 Gateway Time-out</h1></center> <hr><center>nginx</center> </body> </html>      



![Image](https://github.com/praxisdigital/moodle-block_sharing_cart/assets/2778015/34b3b035-b8dc-4713-bcec-40618bd7bb76)

**Comment by mcardle** [comment] 2023-11-16 14:38
@superfoght 

tabtopics is a 3. party plugin and is not Moodle standard. Do they want to pay for it?

**Comment by superfoght** [comment] 2023-11-16 16:06
True.. And I don't know.... But there is something completely wrong with the course. I can't even take a backup of it..

**Comment by mcardle** [comment] 2023-11-23 08:07
Bo needs help to debug and find out, why the course is failing. You cannot even make a normal backup/restore in Moodle, so we need to fix that first.

**Comment by sampraxis** [comment] 2023-11-23 13:32
@superfoght 
I could do the backup with the whole course and specific section "4.4"  without any issue.
Maybe it's an issue for a specific user?

**Comment by superfoght** [comment] 2023-11-23 13:34
@sampraxis could you also copy it with the sharing cart?

**Comment by sampraxis** [comment] 2023-12-04 10:48
The profiling of sharing cart is showing that plugin do a lot of database calls.
The profiling tells us that the process of the backup only takes under a minute, but the response from the server got stuck under the backup process and cause the request to timeout after a while.
(Not sure if we can 100% trust the profiling time)

![Image](https://github.com/praxisdigital/moodle-block_sharing_cart/assets/41996743/e1a4685b-1268-4d50-a967-6a793e8acd32)

**Comment by superfoght** [comment] 2023-12-06 09:26
I'm not sure if there is something I should do or reply to the client? Are we still investigating?

**Comment by sampraxis** [comment] 2023-12-11 08:18
@superfoght 
Yes.
But we cannot reproduce the same error with our test sites.
The last resolve might be that they have to backup the original course and restore the course again, then try to copy something to sharing cart.
If the issue doesn't goes away just contact me.

**Comment by sampraxis** [comment] 2024-01-02 08:34
Related issue: #118

**Comment by sampraxis** [comment] 2024-01-26 10:51
@superfoght 
This issue might also related to the massive amount of duplicated badges.
We got them deleted from moodle.
Could you check, if everything is working again?

**Comment by superfoght** [comment] 2024-01-26 12:21
@sampraxis yeah I got it to work. But it looksl it still takes a lot of time for that particular ad-hoc task to activate? I had to run it manually before it was copied.

**Comment by sampraxis** [comment] 2024-01-29 07:58
@superfoght 
I think it's because there is too many task that are waiting to be run.
For now they have to use the classic mode (immediate), indtil most of them are complete.

**Comment by mcardle** [comment] 2024-02-23 07:35
Bo has confirmed, that the tasks has passed through the system - closing issue

**Closed by mcardle** 2024-02-23 07:35 UTC
Labels: bug
