### ISSUE TITLE
Bug, on mitnielsbrock when inserting a section

### ISSUE THREAD

**Issue by neeesn** [praxisdigital/moodle-block_sharing_cart#106] opened 2023-11-22 11:16 UTC
Theres an error when inserting a specifik section copied from another course.

![Image](https://github.com/praxisdigital/moodle-block_sharing_cart/assets/1931926/c3456a0c-6c35-46f9-a08e-613c977805c5)

The user Stefan Emil Søltoft ([ssol@niels.brock.dk](mailto:ssol@niels.brock.dk))
He is copying  https://www.mitnielsbrock.dk/course/view.php?id=46736&section=6
Section: kap. 7 Virksomhedens interessenter
and he tries to copy to: https://www.mitnielsbrock.dk/course/view.php?id=57948&section=1

I have tryed as admin user and get the same error.

**Comment by neeesn** [comment] 2023-11-22 11:18
Hubspot: https://app-eu1.hubspot.com/contacts/25645903/record/0-5/2038978767

**Comment by mcardle** [comment] 2023-11-22 11:38
This is an index-issue duplicate entry in database.

**Comment by frederikmillingpytlick** [comment] 2023-11-23 14:27
The course module causing the issue is https://www.mitnielsbrock.dk/mod/resource/view.php?id=1469268

It somehow backs up a totally different course module's mdl_course_modules_viewed records????

**Comment by frederikmillingpytlick** [comment] 2023-11-27 09:04
When the sharing cart makes a backup of the module, it determines that userdata should not be copied.

But then it proceeds to copy the completion data from the activity and doesn't copy the users resulting in Moodle not being able to map the id's to actual users. Moodle defaults to 0 if no mapping is found and this is how the invalid records appear.

**Comment by frederikmillingpytlick** [comment] 2023-11-27 12:38
**I've created a tracker issue:**
https://tracker.moodle.org/browse/MDL-80269

**Comment by frederikmillingpytlick** [comment] 2023-11-27 12:40
@neeesn should i create a patch for Moodle HQ? - I'm unsure whether the customer should pay for this

**Comment by frederikmillingpytlick** [comment] 2023-11-29 07:56
@neeesn I've done a backup/restore of the whole course on their live site. In the restored course the sharing cart works fine.

It'd take a lot of time to debug the issue and would require us to copy their live data. Would it be an acceptable solution to just create a new course from the original like i did?

**Comment by frederikmillingpytlick** [comment] 2023-12-14 09:32
closing issue

**Closed by frederikmillingpytlick** 2023-12-14 09:32 UTC
Labels: bug

**Comment by neeesn** [comment] 2023-12-15 13:18
The issue has been declined since they cant reproduce it. Please have a look at the issue again.

**Comment by frederikmillingpytlick** [comment] 2023-12-15 13:42
@neeesn Sam and I have been unable to reproduce it in Moodle without the sharing cart, so fixing it in the sharing cart should be adequate. Moodle HQ won't allow patches without a reproducible error

@sampraxis has a fix coming up for the sharing cart

See: #111
